services:
  deming:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ### PLEASE DISABLE AFTER THE FIRST RUN FOR OPTIMIZATION PRODUCTION
      - DB_SLEEP=10
      ### PLEASE DISABLE FOR PRODUCTION
      - USE_DEMO_DATA=1
      ### PLEASE DISABLE FOR PRODUCTION
      #- RESET_DB=FR #EN OR FR
      ### PLEASE AFTER ONE RUN DISABLE FOR OPTIMIZATION
      - UPLOAD_DB_ISO27001=FR #EN OR FR
      ### PLEASE AFTER ONE RUN DISABLE FOR OPTIMIZATION
      - INITIAL_DB=FR #EN OR FR
      - TZ=Europe/Paris
      - APP_ENV=production
      - APP_FORCE_HTTPS=false
    volumes:
      - .env:/var/www/deming/.env
      - ./docker/custom/deming.php:/var/www/deming/config/deming.php
      - ./docker/custom/Kernel.php:/var/www/deming/app/Console/Kernel.php
      - ./docker/custom/app.php:/var/www/deming/config/app.php
    ports:
      - 80:8000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOTPASSWORD}'
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 3
### PLEASE ENABLE FOR PERSISTENT DATABASE DATA
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
